# Generated by Django 3.1.7 on 2021-04-11 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Person', '0002_auto_20210401_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
