# Generated by Django 3.1.7 on 2021-04-15 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0003_auto_20210411_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_to_father', to='Person.personmodel'),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_to_mother', to='Person.personmodel'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='first_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='info',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='place_of_birth',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='place_of_death',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
