# Generated by Django 3.1.7 on 2021-04-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0004_auto_20210415_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='photos',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='photos/', width_field=100),
        ),
    ]
