# Generated by Django 3.1.7 on 2021-04-17 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0005_personmodel_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personmodel',
            name='photos',
        ),
        migrations.AddField(
            model_name='personmodel',
            name='siblings',
            field=models.ManyToManyField(blank=True, related_name='_personmodel_siblings_+', to='Person.PersonModel'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_children', to='Person.personmodel'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_children', to='Person.personmodel'),
        ),
    ]
