# Generated by Django 3.1.7 on 2021-04-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0008_auto_20210417_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD format', null=True),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD format', null=True),
        ),
    ]
