# Generated by Django 3.1.7 on 2021-04-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0010_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Person.usermodel'),
        ),
    ]
