# Generated by Django 3.1.7 on 2021-05-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0012_auto_20210424_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
