# Generated by Django 3.1.7 on 2021-05-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0013_auto_20210501_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='DD/MM/YYYY', null=True),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='DD/MM/YYYY', null=True),
        ),
    ]
