# Generated by Django 3.1.7 on 2021-05-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0014_auto_20210508_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
