# Generated by Django 3.1.7 on 2021-05-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0015_auto_20210508_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personmodel',
            old_name='patronymic_name',
            new_name='patronymic',
        ),
    ]
