# Generated by Django 3.1.7 on 2021-05-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0016_auto_20210508_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personmodel',
            old_name='photos',
            new_name='photo',
        ),
    ]
