# Generated by Django 3.1.7 on 2021-05-09 12:55

import Person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0017_auto_20210508_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=Person.models.photo_file_name, validators=[Person.models.validate_image]),
        ),
    ]
