# Generated by Django 3.1.7 on 2021-05-09 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0018_auto_20210509_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_children', to='Person.personmodel'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='info',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_children', to='Person.personmodel'),
        ),
    ]
